config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: 'matrices#index'

  resources :matrices do
    resources :matrix_steps, as: 'steps', only: [:index, :show, :update]
    resources :criteria, except: [:show, :index]
    resources :options, except: [:show, :index]
    member do
      post 'copy'
    end
  end

  resources :users, only: [:show]

end

app/controllers/matrices_controller.rb
class MatricesController < CrudController
  helper_method :options_sort_method, :options_sort_direction,
                :options_sort_criterium
  before_action :set_matrix, only: [:show, :edit, :update, :destroy, :copy]
  before_action :set_criteria, only: [:show, :edit, :update]
  before_action :set_options, only: [:show, :edit, :update]
  before_action :authenticate_matrix_owner, only: [:edit, :update, :destroy]

  def index
    @my_matrices = Matrix.where(owner: current_user)
                         .order(created_at: :desc).last(5)
    @krystan_matrices = Matrix.where(owner_id: 1)
                              .order(created_at: :desc).last(5)
    @other_matrices = Matrix.where.not(owner: current_user)
                            .order(created_at: :desc).last(5)
  end

  def show
  end

  def new
    @matrix = Matrix.new
  end

  def edit
  end

  def create
    @matrix = current_user.matrices.new(matrix_params)

    if @matrix.save
      flash[:notice] = "#{@matrix.name} was successfully created."
      redirect_to matrix_steps_path(@matrix)
    else
      render :new
    end
  end

  def update
    if @matrix.update(matrix_params)
      flash[:notice] = "#{@matrix.name} was successfully updated."
      redirect_to edit_matrix_path(@matrix)
    else
      render :edit
    end
  end

  def destroy
    @matrix.destroy
    redirect_to matrices_path,
                notice: "#{@matrix.name} was successfully deleted."
  end

  def copy
    new_matrix = @matrix.amoeba_dup
    new_matrix.owner = current_user
    if new_matrix.save
      flash[:notice] = "#{new_matrix.name} was successfully created."
      redirect_to edit_matrix_path(new_matrix)
    else
      flash[:alert] = "Sorry, #{@matrix.name} could not be copied."
      @matrix = new_matrix
      render :show
    end
  end

  private

  def matrix_params
    score_attributes = [:id, :amount, :criterium_id, :option_id, :bin_id]
    option_attributes = [:id, :name, scores_attributes: score_attributes]
    params.require(:matrix).permit(:name, options_attributes: option_attributes)
  end

  def set_matrix
    @matrix = Matrix.find(params[:id])
  end

  def set_criteria
    @criteria = @matrix.criteria.sort_by(&:weight).reverse
    # TODO: order by user selection
  end

  def set_options
    @options = @matrix.options_by(options_sort_method,
                                  options_sort_direction,
                                  options_sort_criterium)
  end

  def options_sort_method
    if action_name == 'show'
      params[:sort_options_by] || 'total_score'
    else
      params[:sort_options_by] || 'name'
    end
  end

  def options_sort_direction
    if action_name == 'show'
      params[:options_direction] || 'desc'
    else
      params[:options_direction] || 'asc'
    end
  end

  def options_sort_criterium
    params[:sort_by_criterium] || nil
  end

  def criteria_count
    @matrix.criteria.count
  end
  helper_method :criteria_count
end

app/views/matrices/_form.html.erb
<div class="well">
  <%= form_for(@matrix) do |f| %>
    <%= render 'layouts/errors', object: @matrix %>

    <div class="field">
      <%= f.label :name, 'Matrix Name', class: "control-label" %>
      <div class="dec-input-wrapper">
        <%= f.text_field :name, class: "form-control", placeholder: "What is your question?" %>
      </div>
    </div>

    <div class="actions">
      <%= f.submit id: 'save-matrix', class: "btn btn-success" %>
      <% if edit %>
        <%= link_to matrix_path(@matrix),
        data: { confirm: 'You sure?',
          method: 'delete'},
          id: 'delete-matrix',
          class: 'btn btn-small btn-danger' do %>
          Delete <%= @matrix.name %>
          <% end %>
      <% end %>
    </div>
  <% end %>
</div>

app/views/matrices/_matrices_list.html.erb
<% if matrices.any? %>
  <div class="col-sm-<%= column_size %>">
    <h5><%= heading %></h5>
    <% if link_path %>
      <%= link_to 'See all', link_path %>
    <% else %>
      <br>
    <% end %>
    <ul class="nav nav-pills nav-stacked fa-ul">
      <% matrices.each do |matrix| %>
        <li>
          <%= link_to matrix do %>
            <% if matrix.winner? %>
              <span class="dec-winner">
                <i class="fa-li fa fa-check" aria-hidden="true"></i><%= matrix.name %><br>
                (winner: <%= matrix.winner_name %>)
              </span>
            <% else %>
              <span class="dec-tie">
                <i class="fa-li fa fa-question" aria-hidden="true"></i>  <%= matrix.name %>
              </span>
            <% end %>
          <% end %>
        </li>
      <% end %>
    </ul>
  </div>
<% end %>

app/views/matrices/_matrix.html.erb
<div class="table-responsive">
  <table class="table table-hover table-bordered dec-matrix">
    <thead>
      <tr>
        <th rowspan="2">
          <%= sort_options 'name', title: 'Options' %>
          <% if view == 'edit' %>
            <%= link_to new_matrix_option_path(@matrix),
                        id: 'new-option',
                        class: 'btn-circle' do %>
              <%= fa_icon 'plus' %>
            <% end %>
          <% end %>
        </th>
        <% unless view == 'edit' %>
          <th rowspan="2">
            <%= sort_options 'total_score', title: 'Total Scores'  %>
          </th>
        <% end %>
        <th colspan="<%= criteria_count %>">
          Criteria
          <% if view == 'edit' %>
            <%= link_to new_matrix_criterium_path(@matrix),
                        id: 'new-criterium',
                        class: 'btn-circle' do %>
              <%= fa_icon 'plus' %>
            <% end %>
          <% end %>
        </th>
      </tr>
      <tr>
        <%= render @criteria, view: view %>
      </tr>
    </thead>
    <tbody>
      <%= render @options, view: view %>
    </tbody>
  </table>
</div>

app/views/matrices/edit.html.erb
<% header "#{@matrix.name}" %>

<% content_for :header_buttons do %>
  <a id='show-matrix-form' data-toggle="collapse" href="#editMatrixName" aria-expanded="false" aria-controls="editMatrixName" class="btn-circle">
    <i class="fa fa-pencil" aria-hidden="true"></i>
  </a>
  <%= link_to copy_matrix_path(@matrix), class: "btn-circle", data: { confirm: 'Please confirm you would like to copy this matrix', method: 'post' } do %>
    <i class="fa fa-copy" aria-hidden="true"></i>
  <% end %>
<% end %>

<%= render 'layouts/progress', percent: 90 %>

<div class="collapse" id="editMatrixName">
  <%= render 'form', edit: true %>
</div>

<h5><b>Rate Your Options</b></h5>
<div class="dec-form-description">
  Select a rating for every criterium/option intersection. Percentages next to criteria reflect the weight that will be applied to ratings in that criterium.
</div>

<div id="matrix">
  <%= render 'matrix', view: 'edit' %>
</div>

<%= link_to 'View Your Results!', @matrix, class: 'btn btn-block btn-lg btn-primary', id: 'view-results' %>

app/views/matrices/edit.js.erb
$('#matrix').html('<%= j render "matrix", view: "edit" %>');
$('.dec-table-form input[type=submit]').remove();

app/views/matrices/index.html.erb
<div class="jumbotron">
  <h1>Life is full of tough decisions.</h1>
  <p>
    Decision matrices help people and teams choose wisely based on priorities and values.
  </p>
  <%= link_to 'Click here to start a new decision', new_matrix_path, id: 'new-matrix', class: 'btn btn-success btn-lg btn-block' %>
</div>

<div class="row" id="examples">
  <%= render 'matrices_list', matrices: @my_matrices, heading: 'Your decisions:', column_size: 4, link_path: current_user %>
  <% if User.exists?(1) %>
    <%= render 'matrices_list', matrices: @krystan_matrices, heading: 'Example decisions:', column_size: 4, link_path: User.find(1) %>
  <% end %>
  <%= render 'matrices_list', matrices: @other_matrices, heading: "Other users' decisions:", column_size: 4, link_path: nil %>
</div>

app/views/matrices/new.html.erb
<% header 'Name Your Decision' %>

<%= render 'layouts/progress', percent: 5 %>

<h5><b>Step 1:</b> What question are you trying to answer?</h5>
<div class="dec-form-description">
  For example:
  <div class="row">
    <div class="col-sm-6">
      <ul>
        <li>The Big Dig: Go or No-Go?</li>
        <li>What should we eat for dinner?</li>
      </ul>
    </div>
    <div class="col-sm-6">
      <ul>
        <li>How should I prioritize my bucket list?</li>
        <li>Who should I nominate for the Supreme Court?</li>
      </ul>
    </div>
  </div>
  <div class="alert alert-tip" >
    <b>TIP:</b> If this is your first visit to DECIDED, check out some <%= link_to 'example decisions', root_path + '#examples' %> before beginning.
  </div>
</div>

<div class="well">
  <%= render 'form', edit: false %>
</div>

app/views/matrices/show.html.erb
<% header @matrix.name %>

<%= render 'layouts/progress', percent: 100 %>

<%= render 'layouts/errors', object: @matrix %>

<div class="dec-form-description">
  <% if current_matrix_owner? %>
    <%= link_to 'Edit this matrix', edit_matrix_path(@matrix), id: 'edit-matrix' %>
  <% elsif user_signed_in? %>
    <p>
      Read only. Log in as the matrix owner or <%= link_to 'copy this matrix', copy_matrix_path(@matrix), data: { confirm: 'Please confirm you would like to copy this matrix', method: 'post' } %> to edit.
    </p>
  <% else %>
    <p>
      Read only. Log in to edit or create matrices.
    </p>
  <% end %>
</div>

<% if @matrix.winner? %>
  <h5><b>Winning Option:</b> <%= @matrix.winner_name %></h5>
  <% if current_matrix_owner? %>
    <p>
      If you agree with this choice, you have made a decision! If not, re-evaulate your rankings, criteria, and criteria weighting.
    </p>
  <% end %>
<% else %>
  <% if @matrix.tie? %>
    <h5>We have a tie!</h5>
    <% if current_matrix_owner? %>
      <p>
        Please re-evaulate your rankings, criteria, and criteria weighting.
      </p>
    <% end %>
  <% end %>
<% end %>

<div id="matrix">
  <%= render 'matrix', view: 'show' %>
</div>

<p>
  This matrix was created by <%= link_to @matrix.owner.name, @matrix.owner %>. <span class="pull-right"><%= link_to 'Create a new matrix!', new_matrix_path %></span>
</p>

app/views/matrices/show.js.erb
$('#matrix').html('<%= j render "matrix", view: "show" %>');