config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: 'matrices#index'

  resources :matrices do
    resources :matrix_steps, as: 'steps', only: [:index, :show, :update]
    resources :criteria, except: [:show, :index]
    resources :options, except: [:show, :index]
    member do
      post 'copy'
    end
  end

  resources :users, only: [:show]

end

app/models/option.rb
class Option < ActiveRecord::Base
  belongs_to :matrix
  # matrix(force_reload = false)
  # matrix=(associate)
  # build_matrix(attributes = {})
  # create_matrix(attributes = {})
  # create_matrix!(attributes = {})
  validates :matrix, presence: true

  has_many :scores, dependent: :destroy
  # scores(force_reload = false)
  # scores<<(object, ...)
  # scores.delete(object, ...)
  # scores.destroy(object, ...)
  # scores=(objects)
  # score_ids
  # score_ids=(ids)
  # scores.clear
  # scores.empty?
  # scores.size
  # scores.find(...)
  # scores.where(...)
  # scores.exists?(...)
  # scores.build(attributes = {}, ...)
  # scores.create(attributes = {})
  # scores.create!(attributes = {})
  accepts_nested_attributes_for :scores

  has_many :criteria, through: :scores
  # criteria(force_reload = false)
  # criteria<<(object, ...)
  # criteria.delete(object, ...)
  # criteria.destroy(object, ...)
  # criteria=(objects)
  # criterium_ids
  # criterium_ids=(ids)
  # criteria.clear
  # criteria.empty?
  # criteria.size
  # criteria.find(...)
  # criteria.where(...)
  # criteria.exists?(...)
  # criteria.build(attributes = {}, ...)
  # criteria.create(attributes = {})
  # criteria.create!(attributes = {})

  validates :name, presence: true, uniqueness: { scope: :matrix_id }

  def get_criterium_score(criterium)
    scores.find_by(criterium: criterium)
  end

  def criterium_score(criterium)
    criterium_score_record = get_criterium_score(criterium)
    if criterium_score_record
      criterium_score_record.amount
    else
      0
    end
  end

  def criterium_score_description(criterium)
    criterium_score_record = get_criterium_score(criterium)
    if criterium_score_record
      if criterium_score_record.bin
        criterium_score_record.bin.description
      end
    end
  end

  def weighted_criterium_score(criterium)
    (criterium_score(criterium) * criterium.weight).round(0)
  end

  def total_score
    total = 0
    criteria.each do |criterium|
      total += weighted_criterium_score(criterium)
    end
    total
  end
end

app/controllers/options_controller.rb
class OptionsController < MatricesChildrenController
  before_action :set_option, only: [:edit, :update, :destroy]

  def new
    @option = @matrix.options.new
  end

  def edit
  end

  def create
    @option = @matrix.options.new(option_params)

    if @option.save
      redirect_to edit_matrix_path(@matrix),
                  notice: "#{@option.name} was successfully created."
    else
      render :new
    end
  end

  def update
    if @option.update(option_params)
      redirect_to edit_matrix_path(@matrix),
                  notice: "#{@option.name} was successfully updated."
    else
      render :edit
    end
  end

  def destroy
    @option.destroy
    redirect_to edit_matrix_path(@matrix),
                notice: "#{@option.name} was successfully deleted."
  end

  private

  def option_params
    params.require(:option).permit(:name)
  end

  def set_option
    @option = Option.find(params[:id])
  end
end

app/views/options/_fields.html.erb
<div class="field">
  <%= f.label :name, 'Option Name', class: "control-label" %>
  <div class="dec-input-wrapper">
    <%= f.text_field :name, class: "form-control" %>
  </div>
</div>

app/views/options/_form.html.erb
<%= form_for [@matrix, @option] do |f| %>
  <%= render 'layouts/errors', object: @option %>

  <%= render 'fields', f: f %>
  <div class="actions">
    <%= f.submit id: 'save-option', class: "btn btn-success" %>
  </div>
<% end %>

app/views/options/_option.html.erb
<tr>
  <td><%= option.name %>
    <% if view == 'edit' %>
      <div>
        <%= link_to edit_matrix_option_path(@matrix, option),
                    id: "edit-option-#{option.id}",
                    class: 'btn-circle' do %>
          <i class="fa fa-pencil" aria-hidden="true"></i>
        <% end %>
        <%= link_to matrix_option_path(@matrix, option),
                    data: { confirm: 'You sure?',
                            method: 'delete'},
                    id: "delete-option-#{option.id}",
                    class: 'btn-circle' do %>
          <i class="fa fa-times" aria-hidden="true"></i>
        <% end %>
      </div>
    <% else %>
      <% if @matrix.winning_options.include? option %>
        <div class="collapse dec-result" id="winner">
          <% if @matrix.tie? %>
            <i class="fa fa-question fa-2x dec-tie" aria-hidden="true"></i>
          <% else %>
            <i class="fa fa-check fa-2x dec-winner" aria-hidden="true"></i>
          <% end %>
        </div>
      <% end %>
    <% end %>
  </td>
  <% unless view == 'edit' %>
    <td class="dec-table-score">
      <div class="dec-table-score-weighted">
        <%= option.total_score %>
      </div>
    </td>
  <% end %>
  <% @criteria.each do |criterium| %>
    <td class="dec-table-score">
      <% if view == 'edit' %>
        <%= render 'scores/form', criterium: criterium, option: option %>
      <% else %>
        <div class="dec-table-score-weighted">
          <%= option.weighted_criterium_score(criterium) %>
        </div>
        <div>
          <%= option.criterium_score(criterium) %>
          <% unless option.criterium_score_description(criterium).blank? %>
            : <%= option.criterium_score_description(criterium) %>
          <% end %>
        </div>
      <% end %>
    </td>
  <% end %>
</tr>

app/views/options/edit.html.erb
<% header @matrix.name %>

<h5>Edit Option: <%= @option.name %></h5>

<div class="well">
  <%= render 'form' %>
</div>

<%= link_to 'Back', edit_matrix_path(@matrix) %>

app/views/options/new.html.erb
<% header @matrix.name %>

<h5>New Option</h5>

<div class="well">
  <%= render 'form' %>
</div>

<%= link_to 'Back', edit_matrix_path(@matrix) %>